"""Added SoS

Revision ID: 0c6701691e1a
Revises: 6545aee8ea07
Create Date: 2024-01-06 17:52:28.869368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6701691e1a'
down_revision = '6545aee8ea07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_of_schedule', sa.Numeric(precision=10, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('strength_of_schedule')

    # ### end Alembic commands ###
