"""Added fields to user, team, and created Game

Revision ID: 403a41eaa8c8
Revises: 0c6701691e1a
Create Date: 2024-01-11 19:30:29.521295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403a41eaa8c8'
down_revision = '0c6701691e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.Integer(), nullable=True),
    sa.Column('away_team', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('loser', sa.Integer(), nullable=True),
    sa.Column('isTie', sa.Boolean(), nullable=True),
    sa.Column('timeStarted', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['teams.id'], name=op.f('fk_games_away_team_teams')),
    sa.ForeignKeyConstraint(['home_team'], ['teams.id'], name=op.f('fk_games_home_team_teams')),
    sa.ForeignKeyConstraint(['loser'], ['teams.id'], name=op.f('fk_games_loser_teams')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_games_week_id_weeks')),
    sa.ForeignKeyConstraint(['winner'], ['teams.id'], name=op.f('fk_games_winner_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('alt_color', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_team', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_team')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('alt_color')
        batch_op.drop_column('color')

    op.drop_table('games')
    # ### end Alembic commands ###
