"""added opponent wins, losses, and ties to record

Revision ID: 50dada9f1bff
Revises: eced0d7fbc7f
Create Date: 2024-01-12 20:18:38.463240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dada9f1bff'
down_revision = 'eced0d7fbc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_ties', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('opponent_ties')
        batch_op.drop_column('opponent_losses')
        batch_op.drop_column('opponent_wins')

    # ### end Alembic commands ###
