"""Added year to the game

Revision ID: acf29aad14ca
Revises: 50dada9f1bff
Create Date: 2024-01-16 16:16:20.286843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf29aad14ca'
down_revision = '50dada9f1bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_year_id_years'), 'years', ['year_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_year_id_years'), type_='foreignkey')
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###
