"""Added deleted field to users

Revision ID: ca623e4d8f32
Revises: 3aa5e55dbb4f
Create Date: 2023-12-28 11:57:02.346472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca623e4d8f32'
down_revision = '3aa5e55dbb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('wins_pool', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wins_pool_user_draft_pick_id_user_draft_picks', type_='foreignkey')
        batch_op.drop_column('user_draft_pick_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wins_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_draft_pick_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_wins_pool_user_draft_pick_id_user_draft_picks', 'user_draft_picks', ['user_draft_pick_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
